### ISSUE TITLE
Add Steps for Running iOS Project

### ISSUE THREAD

**Issue by bmeverett** [sandoche/Infinideas-app#67]
HI guys 👋 

Thanks for making this! I was curious what this was about so I decided to build the iOS project from source. I've never used flutter before so maybe adding some build steps to the README would be helpful. I'm happy to add this as a PR.

Here's what I came up with to get it to build.
Prerequisites 
- [CocoaPods](https://cocoapods.org)
- [Flutter](https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v1.12.13+hotfix.7-stable.zip) 
  - [instructions for MacOS](https://flutter.dev/docs/get-started/install/macos)

1. Navigate to root directory. 
2. Run `flutter packages get`
3. `cd ios/ && pod install` 
4. Open the `Runner .xcworkspac`
5. Build and run the project

**Comment by sandoche** [comment]
Hey can you add this to the readme and do the PR it's very good.
